# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='a.proto',
  package='',
  serialized_pb='\n\x07\x61.proto\"@\n\x0b\x65ntity_attr\x12\x0f\n\x07\x61ttr_id\x18\x01 \x02(\x05\x12\x11\n\tattribute\x18\x02 \x02(\x0c\x12\r\n\x05value\x18\x03 \x03(\x0c\"\x81\x01\n\x0b\x65ntity_desc\x12\x11\n\tentity_id\x18\x01 \x02(\x05\x12\x13\n\x0b\x65ntity_name\x18\x02 \x02(\x0c\x12\r\n\x05opt_1\x18\x03 \x01(\x0c\x12\r\n\x05opt_2\x18\x04 \x01(\x0c\x12 \n\nattributes\x18\x05 \x03(\x0b\x32\x0c.entity_attr\x12\n\n\x02my\x18\x06 \x01(\x07')




_ENTITY_ATTR = _descriptor.Descriptor(
  name='entity_attr',
  full_name='entity_attr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr_id', full_name='entity_attr.attr_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='entity_attr.attribute', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='entity_attr.value', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=11,
  serialized_end=75,
)


_ENTITY_DESC = _descriptor.Descriptor(
  name='entity_desc',
  full_name='entity_desc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='entity_desc.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='entity_desc.entity_name', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_1', full_name='entity_desc.opt_1', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_2', full_name='entity_desc.opt_2', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='entity_desc.attributes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='my', full_name='entity_desc.my', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=207,
)

_ENTITY_DESC.fields_by_name['attributes'].message_type = _ENTITY_ATTR
DESCRIPTOR.message_types_by_name['entity_attr'] = _ENTITY_ATTR
DESCRIPTOR.message_types_by_name['entity_desc'] = _ENTITY_DESC

class entity_attr(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITY_ATTR

  # @@protoc_insertion_point(class_scope:entity_attr)

class entity_desc(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITY_DESC

  # @@protoc_insertion_point(class_scope:entity_desc)


# @@protoc_insertion_point(module_scope)
