/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Mon Mar  9 23:12:11 2015. */

#ifndef PB_SDP_PB_H_INCLUDED
#define PB_SDP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _LOGIN_STATUS_TYPE {
    LOGIN_STATUS_TYPE_LOGIN_STATUS_UNKOWN = 101,
    LOGIN_STATUS_TYPE_LOGIN_STATUS_SUCCESS = 102,
    LOGIN_STATUS_TYPE_LOGIN_STATUS_ID_INEXIST = 103,
    LOGIN_STATUS_TYPE_LOGIN_STATUS_ENCODE_EXCEPTION = 104
} LOGIN_STATUS_TYPE;

typedef enum _WORK_ALARM_TYPE {
    WORK_ALARM_TYPE_WORK_ALARM_UNKOWN = 0,
    WORK_ALARM_TYPE_WORK_ALARM_CAMERA_COVER = 101,
    WORK_ALARM_TYPE_WORK_ALARM_ILLEGAL_INSERT = 102,
    WORK_ALARM_TYPE_WORK_ALARM_TEMPERATURE = 103,
    WORK_ALARM_TYPE_WORK_ALARM_GAS = 104,
    WORK_ALARM_TYPE_WORK_ALARM_FPRINT_ERROR = 105,
    WORK_ALARM_TYPE_WORK_ALARM_KEY_ERROR = 106,
    WORK_ALARM_TYPE_WORK_ALARM_EMERGECY = 107
} WORK_ALARM_TYPE;

typedef enum _LOCK_STATUS_TYPE {
    LOCK_STATUS_TYPE_LOCK_STATUS_UNKOWN = 0,
    LOCK_STATUS_TYPE_LOCK_STATUS_CLOSE = 101,
    LOCK_STATUS_TYPE_LOCK_STATUS_OPEN = 102
} LOCK_STATUS_TYPE;

typedef enum _FAULT_ALARM_TYPE {
    FAULT_ALARM_TYPE_FAULT_ALARM_UNKOWN = 0,
    FAULT_ALARM_TYPE_FAULT_ALARM_CAMERA = 101,
    FAULT_ALARM_TYPE_FAULT_ALARM_RFID = 102,
    FAULT_ALARM_TYPE_FAULT_ALARM_TEMPERATURE = 103,
    FAULT_ALARM_TYPE_FAULT_ALARM_GSM = 104,
    FAULT_ALARM_TYPE_FAULT_ALARM_FPRINT = 105,
    FAULT_ALARM_TYPE_FAULT_ALARM_MOTOR = 106
} FAULT_ALARM_TYPE;

typedef enum _BATTERY_STATUS_TYPE {
    BATTERY_STATUS_TYPE_BATTERY_STATUS_UNKOWN = 0,
    BATTERY_STATUS_TYPE_BATTERY_STATUS_SUPPLY = 101,
    BATTERY_STATUS_TYPE_BATTERY_STATUS_50P = 102,
    BATTERY_STATUS_TYPE_BATTERY_STATUS_20P = 103,
    BATTERY_STATUS_TYPE_BATTERY_STATUS_5P = 104
} BATTERY_STATUS_TYPE;

typedef enum _OPEN_PATTERN_TYPE {
    OPEN_PATTERN_TYPE_OPEN_PATTERN_UNKOWN = 0,
    OPEN_PATTERN_TYPE_OPEN_PATTERN_KEY = 101,
    OPEN_PATTERN_TYPE_OPEN_PATTERN_RFID = 102,
    OPEN_PATTERN_TYPE_OPEN_PATTERN_FPRINT = 103,
    OPEN_PATTERN_TYPE_OPEN_PATTERN_REMOTE = 104
} OPEN_PATTERN_TYPE;

typedef enum _PHONE_AUTH_TYPE {
    PHONE_AUTH_TYPE_PHONE_AUTH_INVALID = 0,
    PHONE_AUTH_TYPE_PHONE_AUTH_CALL = 101,
    PHONE_AUTH_TYPE_PHONE_AUTH_SMS = 102
} PHONE_AUTH_TYPE;

typedef enum _PHONE_STATUS_TYPE {
    PHONE_STATUS_TYPE_PHONE_STATUS_INVALID = 0,
    PHONE_STATUS_TYPE_PHONE_STATUS_SUCCESS = 101,
    PHONE_STATUS_TYPE_PHONE_STATUS_LATEST = 102
} PHONE_STATUS_TYPE;

typedef enum _KEY_TYPE {
    KEY_TYPE_KEY_INVALID = 0,
    KEY_TYPE_KEY_FPRINT = 1,
    KEY_TYPE_KEY_RFID = 2,
    KEY_TYPE_KEY_KBOARD = 3
} KEY_TYPE;

typedef enum _KEY_AUTH_TYPE {
    KEY_AUTH_TYPE_KEY_AUTH_INVALID = 0,
    KEY_AUTH_TYPE_KEY_AUTH_FOREVER = 1,
    KEY_AUTH_TYPE_KEY_AUTH_ONCE = 2,
    KEY_AUTH_TYPE_KEY_AUTH_WEEKLY = 3
} KEY_AUTH_TYPE;

typedef enum _KEY_STATUS_TYPE {
    KEY_STATUS_TYPE_KEY_STATUS_INVALID = 0,
    KEY_STATUS_TYPE_KEY_STATUS_SUCCESS = 101,
    KEY_STATUS_TYPE_KEY_STATUS_LATEST = 102
} KEY_STATUS_TYPE;

typedef enum _ACCOUNT_STATUS_TYPE {
    ACCOUNT_STATUS_TYPE_ACCOUNT_STATUS_INVALID = 0,
    ACCOUNT_STATUS_TYPE_ACCOUNT_STATUS_SUCCESS = 101,
    ACCOUNT_STATUS_TYPE_ACCOUNT_STATUS_LATEST = 102
} ACCOUNT_STATUS_TYPE;

typedef enum _MOTOR_STATUS_TYPE {
    MOTOR_STATUS_TYPE_MOTOR_STATUS_INVALID = 0,
    MOTOR_STATUS_TYPE_MOTOR_STATUS_OPEN = 101,
    MOTOR_STATUS_TYPE_MOTOR_STATUS_CLOSE = 102
} MOTOR_STATUS_TYPE;

typedef enum _ACCOUNT_MAP_STATUS_TYPE {
    ACCOUNT_MAP_STATUS_TYPE_ACCOUNT_MAP_STATUS_INVALID = 0,
    ACCOUNT_MAP_STATUS_TYPE_ACCOUNT_MAP_STATUS_LATEST = 101,
    ACCOUNT_MAP_STATUS_TYPE_ACCOUNT_MAP_STATUS_UPGRADE = 102,
    ACCOUNT_MAP_STATUS_TYPE_ACCOUNT_MAP_STATUS_FAILURE = 103
} ACCOUNT_MAP_STATUS_TYPE;

typedef enum _KEY_MAP_STATUS_TYPE {
    KEY_MAP_STATUS_TYPE_KEY_MAP_STATUS_INVALID = 0,
    KEY_MAP_STATUS_TYPE_KEY_MAP_STATUS_LATEST = 101,
    KEY_MAP_STATUS_TYPE_KEY_MAP_STATUS_UPGRADE = 102,
    KEY_MAP_STATUS_TYPE_KEY_MAP_STATUS_FAILURE = 103
} KEY_MAP_STATUS_TYPE;

typedef enum _PHONE_MAP_STATUS_TYPE {
    PHONE_MAP_STATUS_TYPE_PHONE_MAP_STATUS_INVALID = 0,
    PHONE_MAP_STATUS_TYPE_PHONE_MAP_STATUS_LATEST = 101,
    PHONE_MAP_STATUS_TYPE_PHONE_MAP_STATUS_UPGRADE = 102,
    PHONE_MAP_STATUS_TYPE_PHONE_MAP_STATUS_FAILURE = 103
} PHONE_MAP_STATUS_TYPE;

typedef enum _LOG_MAP_STATUS_TYPE {
    LOG_MAP_STATUS_TYPE_LOG_MAP_STATUS_INVALID = 0,
    LOG_MAP_STATUS_TYPE_LOG_MAP_STATUS_LATEST = 101,
    LOG_MAP_STATUS_TYPE_LOG_MAP_STATUS_UPGRADE = 102,
    LOG_MAP_STATUS_TYPE_LOG_MAP_STATUS_FAILURE = 103
} LOG_MAP_STATUS_TYPE;

typedef enum _MSG {
    MSG_UNKOWN = 0,
    MSG_REQ_LOGIN = 10001,
    MSG_REP_LOGIN = 10002,
    MSG_REQ_LOGOUT = 10003,
    MSG_REP_LOGOUT = 10004,
    MSG_REQ_KEEP_ALIVE = 10005,
    MSG_REP_KEEP_ALIVE = 10006,
    MSG_REQ_WORK_ALARM = 10007,
    MSG_REP_WORK_ALARM = 10008,
    MSG_REQ_FAULT_ALARM = 10009,
    MSG_REP_FAULT_ALARM = 10010,
    MSG_REQ_BATTERY = 10011,
    MSG_REP_BATTERY = 10012,
    MSG_REQ_OPEN = 10013,
    MSG_REP_OPEN = 10014,
    MSG_REQ_PHONE_ADD = 10015,
    MSG_REP_PHONE_ADD = 10016,
    MSG_REQ_PHONE_MODIFY = 10017,
    MSG_REP_PHONE_MODIFY = 10018,
    MSG_REQ_PHONE_DELETE = 10019,
    MSG_REP_PHONE_DELETE = 10020,
    MSG_REQ_PARAMETERS = 10021,
    MSG_REP_PARAMETERS = 10022,
    MSG_REQ_TIME = 10025,
    MSG_REP_TIME = 10026,
    MSG_REQ_UPGRADE = 10027,
    MSG_REP_UPGRADE = 10028,
    MSG_REQ_MOTOR = 10029,
    MSG_REP_MOTOR = 10030,
    MSG_REQ_ACCOUNT_ADD = 10031,
    MSG_REP_ACCOUNT_ADD = 10032,
    MSG_REQ_ACCOUNT_MODIFY = 10033,
    MSG_REP_ACCOUNT_MODIFY = 10034,
    MSG_REQ_ACCOUNT_DELETE = 10035,
    MSG_REP_ACCOUNT_DELETE = 10036,
    MSG_REQ_FILE_INFO = 10037,
    MSG_REP_FILE_INFO = 10038,
    MSG_REQ_FILE_DATA = 10039,
    MSG_REP_FILE_DATA = 10040,
    MSG_REQ_PASSWORD = 10041,
    MSG_REP_PASSWORD = 10042,
    MSG_REQ_LOG_MAP_CHECK = 10043,
    MSG_REP_LOG_MAP_CHECK = 10044,
    MSG_REQ_LOG_MAP_SYNC = 10045,
    MSG_REP_LOG_MAP_SYNC = 10046,
    MSG_REQ_LOG_CHECK = 10047,
    MSG_REP_LOG_CHECK = 10048,
    MSG_REQ_KEY_MAP_CHECK = 10049,
    MSG_REP_KEY_MAP_CHECK = 10050,
    MSG_REQ_KEY_MAP_SYNC = 10051,
    MSG_REP_KEY_MAP_SYNC = 10052,
    MSG_REQ_KEY_CHECK = 10053,
    MSG_REP_KEY_CHECK = 10054,
    MSG_REQ_PHONE_MAP_CHECK = 10055,
    MSG_REP_PHONE_MAP_CHECK = 10056,
    MSG_REQ_PHONE_MAP_SYNC = 10057,
    MSG_REP_PHONE_MAP_SYNC = 10058,
    MSG_REQ_PHONE_CHECK = 10059,
    MSG_REP_PHONE_CHECK = 10060,
    MSG_REQ_SYNC = 10061,
    MSG_REP_SYNC = 10062,
    MSG_REQ_ACCOUNT_MAP_CHECK = 10063,
    MSG_REP_ACCOUNT_MAP_CHECK = 10064,
    MSG_REQ_ACCOUNT_MAP_SYNC = 10065,
    MSG_REP_ACCOUNT_MAP_SYNC = 10066,
    MSG_REQ_ACCOUNT_CHECK = 10067,
    MSG_REP_ACCOUNT_CHECK = 10068,
    MSG_REQ_ACCOUNT_TO_KEY = 10069,
    MSG_REP_ACCOUNT_TO_KEY = 10070,
    MSG_REQ_ACCOUNT_TO_PHONE = 10071,
    MSG_REP_ACCOUNT_TO_PHONE = 10072,
    MSG_REQ_KEY_ADD = 10073,
    MSG_REP_KEY_ADD = 10074,
    MSG_REQ_KEY_MODIFY = 10075,
    MSG_REP_KEY_MODIFY = 10076,
    MSG_REQ_KEY_DELETE = 10077,
    MSG_REP_KEY_DELETE = 10078,
    MSG_REQ_WELCOME_NOTIFICATION = 20001
} MSG;

/* Struct definitions */
typedef struct _BatteryResponse {
    uint8_t dummy_field;
} BatteryResponse;

typedef struct _FaultAlarmResponse {
    uint8_t dummy_field;
} FaultAlarmResponse;

typedef struct _KeepAliveRequest {
    uint8_t dummy_field;
} KeepAliveRequest;

typedef struct _KeepAliveResponse {
    uint8_t dummy_field;
} KeepAliveResponse;

typedef struct _LogoutRequest {
    uint8_t dummy_field;
} LogoutRequest;

typedef struct _LogoutResponse {
    uint8_t dummy_field;
} LogoutResponse;

typedef struct _OpenResponse {
    uint8_t dummy_field;
} OpenResponse;

typedef struct _PasswordResponse {
    uint8_t dummy_field;
} PasswordResponse;

typedef struct _WorkAlarmResponse {
    uint8_t dummy_field;
} WorkAlarmResponse;

typedef struct _AccountAddRequest {
    bool has_id;
    uint32_t id;
    bool has_name;
    char name[16];
    bool has_occurred_time;
    uint32_t occurred_time;
} AccountAddRequest;

typedef struct _AccountAddResponse {
    bool has_status;
    ACCOUNT_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} AccountAddResponse;

typedef struct _AccountCheckRequest {
    bool has_time;
    uint32_t time;
    bool has_id;
    uint32_t id;
} AccountCheckRequest;

typedef struct _AccountCheckResponse {
    bool has_status;
    ACCOUNT_MAP_STATUS_TYPE status;
} AccountCheckResponse;

typedef struct _AccountDeleteRequest {
    bool has_id;
    uint32_t id;
    bool has_occurred_time;
    uint32_t occurred_time;
} AccountDeleteRequest;

typedef struct _AccountDeleteResponse {
    bool has_status;
    ACCOUNT_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} AccountDeleteResponse;

typedef struct _AccountMapCheckRequest {
    bool has_time;
    uint32_t time;
} AccountMapCheckRequest;

typedef struct _AccountMapCheckResponse {
    bool has_status;
    ACCOUNT_MAP_STATUS_TYPE status;
} AccountMapCheckResponse;

typedef PB_BYTES_ARRAY_T(512) AccountMapSyncRequest_map_t;

typedef struct _AccountMapSyncRequest {
    bool has_time;
    uint32_t time;
    bool has_map;
    AccountMapSyncRequest_map_t map;
} AccountMapSyncRequest;

typedef struct _AccountMapSyncResponse {
    bool has_status;
    ACCOUNT_MAP_STATUS_TYPE status;
} AccountMapSyncResponse;

typedef struct _AccountModifyRequest {
    bool has_id;
    uint32_t id;
    bool has_name;
    char name[16];
    bool has_occurred_time;
    uint32_t occurred_time;
} AccountModifyRequest;

typedef struct _AccountModifyResponse {
    bool has_status;
    ACCOUNT_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} AccountModifyResponse;

typedef struct _AccountToKeyRequest {
    bool has_account_id;
    uint32_t account_id;
    bool has_key_id;
    uint32_t key_id;
    bool has_occurred_time;
    uint32_t occurred_time;
} AccountToKeyRequest;

typedef struct _AccountToKeyResponse {
    bool has_status;
    ACCOUNT_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} AccountToKeyResponse;

typedef struct _AccountToPhoneRequest {
    bool has_account_id;
    uint32_t account_id;
    bool has_phone_id;
    uint32_t phone_id;
    bool has_occurred_time;
    uint32_t occurred_time;
} AccountToPhoneRequest;

typedef struct _AccountToPhoneResponse {
    bool has_status;
    ACCOUNT_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} AccountToPhoneResponse;

typedef struct _BatteryRequest {
    bool has_status;
    BATTERY_STATUS_TYPE status;
    bool has_capacity;
    uint32_t capacity;
    bool has_occurred_time;
    uint32_t occurred_time;
} BatteryRequest;

typedef struct _FaultAlarmRequest {
    bool has_type;
    FAULT_ALARM_TYPE type;
    bool has_status;
    LOCK_STATUS_TYPE status;
    bool has_occurred_time;
    uint32_t occurred_time;
} FaultAlarmRequest;

typedef PB_BYTES_ARRAY_T(16) KeyAddRequest_weekly_t;

typedef PB_BYTES_ARRAY_T(16) KeyAddRequest_code_t;

typedef struct _KeyAddRequest {
    bool has_id;
    uint32_t id;
    bool has_key_type;
    KEY_TYPE key_type;
    bool has_occurred_time;
    uint32_t occurred_time;
    bool has_auth_type;
    KEY_AUTH_TYPE auth_type;
    bool has_weekly;
    KeyAddRequest_weekly_t weekly;
    bool has_start_time;
    uint32_t start_time;
    bool has_end_time;
    uint32_t end_time;
    bool has_code;
    KeyAddRequest_code_t code;
} KeyAddRequest;

typedef struct _KeyAddResponse {
    bool has_status;
    KEY_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} KeyAddResponse;

typedef struct _KeyCheckRequest {
    bool has_time;
    uint32_t time;
    bool has_id;
    uint32_t id;
} KeyCheckRequest;

typedef struct _KeyCheckResponse {
    bool has_status;
    KEY_MAP_STATUS_TYPE status;
} KeyCheckResponse;

typedef struct _KeyDeleteRequest {
    bool has_id;
    uint32_t id;
    bool has_occurred_time;
    uint32_t occurred_time;
} KeyDeleteRequest;

typedef struct _KeyDeleteResponse {
    bool has_status;
    KEY_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} KeyDeleteResponse;

typedef struct _KeyMapCheckRequest {
    bool has_time;
    uint32_t time;
} KeyMapCheckRequest;

typedef struct _KeyMapCheckResponse {
    bool has_status;
    KEY_MAP_STATUS_TYPE status;
} KeyMapCheckResponse;

typedef PB_BYTES_ARRAY_T(512) KeyMapSyncRequest_map_t;

typedef struct _KeyMapSyncRequest {
    bool has_time;
    uint32_t time;
    bool has_map;
    KeyMapSyncRequest_map_t map;
} KeyMapSyncRequest;

typedef struct _KeyMapSyncResponse {
    bool has_status;
    KEY_MAP_STATUS_TYPE status;
} KeyMapSyncResponse;

typedef PB_BYTES_ARRAY_T(16) KeyModifyRequest_weekly_t;

typedef PB_BYTES_ARRAY_T(16) KeyModifyRequest_code_t;

typedef struct _KeyModifyRequest {
    bool has_id;
    uint32_t id;
    bool has_key_type;
    KEY_TYPE key_type;
    bool has_occurred_time;
    uint32_t occurred_time;
    bool has_auth_type;
    KEY_AUTH_TYPE auth_type;
    bool has_weekly;
    KeyModifyRequest_weekly_t weekly;
    bool has_start_time;
    uint32_t start_time;
    bool has_end_time;
    uint32_t end_time;
    bool has_code;
    KeyModifyRequest_code_t code;
} KeyModifyRequest;

typedef struct _KeyModifyResponse {
    bool has_status;
    KEY_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} KeyModifyResponse;

typedef struct _LogCheckRequest {
    bool has_time;
    uint32_t time;
    bool has_id;
    uint32_t id;
} LogCheckRequest;

typedef struct _LogCheckResponse {
    bool has_status;
    LOG_MAP_STATUS_TYPE status;
} LogCheckResponse;

typedef struct _LogMapCheckRequest {
    bool has_time;
    uint32_t time;
} LogMapCheckRequest;

typedef struct _LogMapCheckResponse {
    bool has_status;
    LOG_MAP_STATUS_TYPE status;
} LogMapCheckResponse;

typedef PB_BYTES_ARRAY_T(512) LogMapSyncRequest_map_t;

typedef struct _LogMapSyncRequest {
    bool has_time;
    uint32_t time;
    bool has_map;
    LogMapSyncRequest_map_t map;
} LogMapSyncRequest;

typedef struct _LogMapSyncResponse {
    bool has_status;
    LOG_MAP_STATUS_TYPE status;
} LogMapSyncResponse;

typedef PB_BYTES_ARRAY_T(16) LoginRequest_id_t;

typedef PB_BYTES_ARRAY_T(16) LoginRequest_k1_t;

typedef PB_BYTES_ARRAY_T(16) LoginRequest_k0_t;

typedef struct _LoginRequest {
    bool has_id;
    LoginRequest_id_t id;
    bool has_k1;
    LoginRequest_k1_t k1;
    bool has_version;
    uint32_t version;
    bool has_k0;
    LoginRequest_k0_t k0;
} LoginRequest;

typedef struct _LoginResponse {
    bool has_status;
    LOGIN_STATUS_TYPE status;
    bool has_server_time;
    uint32_t server_time;
} LoginResponse;

typedef struct _MotorRequest {
    bool has_status;
    MOTOR_STATUS_TYPE status;
} MotorRequest;

typedef struct _MotorResponse {
    bool has_status;
    MOTOR_STATUS_TYPE status;
} MotorResponse;

typedef struct _OpenRequest {
    bool has_type;
    OPEN_PATTERN_TYPE type;
    bool has_account_id;
    uint32_t account_id;
    bool has_key_id;
    uint32_t key_id;
    bool has_status;
    LOCK_STATUS_TYPE status;
    bool has_occurred_time;
    uint32_t occurred_time;
} OpenRequest;

typedef PB_BYTES_ARRAY_T(16) PasswordRequest_k0_t;

typedef struct _PasswordRequest {
    bool has_k0;
    PasswordRequest_k0_t k0;
} PasswordRequest;

typedef struct _PhoneAddRequest {
    bool has_id;
    uint32_t id;
    bool has_type;
    PHONE_AUTH_TYPE type;
    bool has_number;
    char number[16];
    bool has_occurred_time;
    uint32_t occurred_time;
} PhoneAddRequest;

typedef struct _PhoneAddResponse {
    bool has_status;
    PHONE_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} PhoneAddResponse;

typedef struct _PhoneCheckRequest {
    bool has_time;
    uint32_t time;
    bool has_id;
    uint32_t id;
} PhoneCheckRequest;

typedef struct _PhoneCheckResponse {
    bool has_status;
    PHONE_MAP_STATUS_TYPE status;
} PhoneCheckResponse;

typedef struct _PhoneDeleteRequest {
    bool has_id;
    uint32_t id;
    bool has_occurred_time;
    uint32_t occurred_time;
} PhoneDeleteRequest;

typedef struct _PhoneDeleteResponse {
    bool has_status;
    PHONE_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} PhoneDeleteResponse;

typedef struct _PhoneMapCheckRequest {
    bool has_time;
    uint32_t time;
} PhoneMapCheckRequest;

typedef struct _PhoneMapCheckResponse {
    bool has_status;
    PHONE_MAP_STATUS_TYPE status;
} PhoneMapCheckResponse;

typedef PB_BYTES_ARRAY_T(512) PhoneMapSyncRequest_map_t;

typedef struct _PhoneMapSyncRequest {
    bool has_time;
    uint32_t time;
    bool has_map;
    PhoneMapSyncRequest_map_t map;
} PhoneMapSyncRequest;

typedef struct _PhoneMapSyncResponse {
    bool has_status;
    PHONE_MAP_STATUS_TYPE status;
} PhoneMapSyncResponse;

typedef struct _PhoneModifyRequest {
    bool has_id;
    uint32_t id;
    bool has_type;
    PHONE_AUTH_TYPE type;
    bool has_number;
    char number[16];
    bool has_occurred_time;
    uint32_t occurred_time;
} PhoneModifyRequest;

typedef struct _PhoneModifyResponse {
    bool has_status;
    PHONE_STATUS_TYPE status;
    bool has_id;
    uint32_t id;
} PhoneModifyResponse;

typedef struct _TimeRequest {
    bool has_time;
    uint32_t time;
} TimeRequest;

typedef struct _TimeResponse {
    bool has_time;
    uint32_t time;
} TimeResponse;

typedef struct _WorkAlarmRequest {
    bool has_type;
    WORK_ALARM_TYPE type;
    bool has_status;
    LOCK_STATUS_TYPE status;
    bool has_occurred_time;
    uint32_t occurred_time;
} WorkAlarmRequest;

typedef struct _Request {
    bool has_login;
    LoginRequest login;
    bool has_logout;
    LogoutRequest logout;
    bool has_keepalive;
    KeepAliveRequest keepalive;
    bool has_workalarm;
    WorkAlarmRequest workalarm;
    bool has_faultalarm;
    FaultAlarmRequest faultalarm;
    bool has_battery;
    BatteryRequest battery;
    bool has_open;
    OpenRequest open;
    bool has_time;
    TimeRequest time;
    bool has_motor;
    MotorRequest motor;
    bool has_account_add;
    AccountAddRequest account_add;
    bool has_account_modify;
    AccountModifyRequest account_modify;
    bool has_account_delete;
    AccountDeleteRequest account_delete;
    bool has_phone_add;
    PhoneAddRequest phone_add;
    bool has_phone_modify;
    PhoneModifyRequest phone_modify;
    bool has_phone_delete;
    PhoneDeleteRequest phone_delete;
    bool has_key_add;
    KeyAddRequest key_add;
    bool has_key_modify;
    KeyModifyRequest key_modify;
    bool has_key_delete;
    KeyDeleteRequest key_delete;
    bool has_password;
    PasswordRequest password;
    bool has_log_map_check;
    LogMapCheckRequest log_map_check;
    bool has_log_map_sync;
    LogMapSyncRequest log_map_sync;
    bool has_log_check;
    LogCheckRequest log_check;
    bool has_account_map_check;
    AccountMapCheckRequest account_map_check;
    bool has_account_map_sync;
    AccountMapSyncRequest account_map_sync;
    bool has_account_check;
    AccountCheckRequest account_check;
    bool has_key_map_check;
    KeyMapCheckRequest key_map_check;
    bool has_key_map_sync;
    KeyMapSyncRequest key_map_sync;
    bool has_key_check;
    KeyCheckRequest key_check;
    bool has_phone_map_check;
    PhoneMapCheckRequest phone_map_check;
    bool has_phone_map_sync;
    PhoneMapSyncRequest phone_map_sync;
    bool has_phone_check;
    PhoneCheckRequest phone_check;
    bool has_account_to_phone;
    AccountToPhoneRequest account_to_phone;
    bool has_account_to_key;
    AccountToKeyRequest account_to_key;
} Request;

typedef struct _Response {
    bool result;
    bool last_response;
    bool has_login;
    LoginResponse login;
    bool has_logout;
    LogoutResponse logout;
    bool has_keepalive;
    KeepAliveResponse keepalive;
    bool has_workalarm;
    WorkAlarmResponse workalarm;
    bool has_faultalarm;
    FaultAlarmResponse faultalarm;
    bool has_battery;
    BatteryResponse battery;
    bool has_open;
    OpenResponse open;
    bool has_time;
    TimeResponse time;
    bool has_motor;
    MotorResponse motor;
    bool has_account_add;
    AccountAddResponse account_add;
    bool has_account_modify;
    AccountModifyResponse account_modify;
    bool has_account_delete;
    AccountDeleteResponse account_delete;
    bool has_phone_add;
    PhoneAddResponse phone_add;
    bool has_phone_modify;
    PhoneModifyResponse phone_modify;
    bool has_phone_delete;
    PhoneDeleteResponse phone_delete;
    bool has_key_add;
    KeyAddResponse key_add;
    bool has_key_modify;
    KeyModifyResponse key_modify;
    bool has_key_delete;
    KeyDeleteResponse key_delete;
    bool has_password;
    PasswordResponse password;
    bool has_log_map_check;
    LogMapCheckResponse log_map_check;
    bool has_log_map_sync;
    LogMapSyncResponse log_map_sync;
    bool has_log_check;
    LogCheckResponse log_check;
    bool has_account_map_check;
    AccountMapCheckResponse account_map_check;
    bool has_account_map_sync;
    AccountMapSyncResponse account_map_sync;
    bool has_account_check;
    AccountCheckResponse account_check;
    bool has_key_map_check;
    KeyMapCheckResponse key_map_check;
    bool has_key_map_sync;
    KeyMapSyncResponse key_map_sync;
    bool has_key_check;
    KeyCheckResponse key_check;
    bool has_phone_map_check;
    PhoneMapCheckResponse phone_map_check;
    bool has_phone_map_sync;
    PhoneMapSyncResponse phone_map_sync;
    bool has_phone_check;
    PhoneCheckResponse phone_check;
    bool has_account_to_phone;
    AccountToPhoneResponse account_to_phone;
    bool has_account_to_key;
    AccountToKeyResponse account_to_key;
} Response;

typedef struct _Message {
    bool has_msg_type;
    MSG msg_type;
    bool has_sequence;
    uint32_t sequence;
    bool has_session_id;
    uint32_t session_id;
    bool has_request;
    Request request;
    bool has_response;
    Response response;
} Message;

/* Default values for struct fields */

/* Initializer values for message structs */
#define LoginRequest_init_default                {false, {0, {0}}, false, {0, {0}}, false, 0, false, {0, {0}}}
#define LoginResponse_init_default               {false, (LOGIN_STATUS_TYPE)0, false, 0}
#define LogoutRequest_init_default               {0}
#define LogoutResponse_init_default              {0}
#define KeepAliveRequest_init_default            {0}
#define KeepAliveResponse_init_default           {0}
#define WorkAlarmRequest_init_default            {false, (WORK_ALARM_TYPE)0, false, (LOCK_STATUS_TYPE)0, false, 0}
#define WorkAlarmResponse_init_default           {0}
#define FaultAlarmRequest_init_default           {false, (FAULT_ALARM_TYPE)0, false, (LOCK_STATUS_TYPE)0, false, 0}
#define FaultAlarmResponse_init_default          {0}
#define BatteryRequest_init_default              {false, (BATTERY_STATUS_TYPE)0, false, 0, false, 0}
#define BatteryResponse_init_default             {0}
#define OpenRequest_init_default                 {false, (OPEN_PATTERN_TYPE)0, false, 0, false, 0, false, (LOCK_STATUS_TYPE)0, false, 0}
#define OpenResponse_init_default                {0}
#define PhoneAddRequest_init_default             {false, 0, false, (PHONE_AUTH_TYPE)0, false, "", false, 0}
#define PhoneModifyRequest_init_default          {false, 0, false, (PHONE_AUTH_TYPE)0, false, "", false, 0}
#define PhoneDeleteRequest_init_default          {false, 0, false, 0}
#define PhoneAddResponse_init_default            {false, (PHONE_STATUS_TYPE)0, false, 0}
#define PhoneModifyResponse_init_default         {false, (PHONE_STATUS_TYPE)0, false, 0}
#define PhoneDeleteResponse_init_default         {false, (PHONE_STATUS_TYPE)0, false, 0}
#define KeyAddRequest_init_default               {false, 0, false, (KEY_TYPE)0, false, 0, false, (KEY_AUTH_TYPE)0, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}}
#define KeyModifyRequest_init_default            {false, 0, false, (KEY_TYPE)0, false, 0, false, (KEY_AUTH_TYPE)0, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}}
#define KeyDeleteRequest_init_default            {false, 0, false, 0}
#define KeyAddResponse_init_default              {false, (KEY_STATUS_TYPE)0, false, 0}
#define KeyModifyResponse_init_default           {false, (KEY_STATUS_TYPE)0, false, 0}
#define KeyDeleteResponse_init_default           {false, (KEY_STATUS_TYPE)0, false, 0}
#define AccountAddRequest_init_default           {false, 0, false, "", false, 0}
#define AccountAddResponse_init_default          {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountModifyRequest_init_default        {false, 0, false, "", false, 0}
#define AccountModifyResponse_init_default       {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountDeleteRequest_init_default        {false, 0, false, 0}
#define AccountDeleteResponse_init_default       {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountToPhoneRequest_init_default       {false, 0, false, 0, false, 0}
#define AccountToKeyRequest_init_default         {false, 0, false, 0, false, 0}
#define AccountToPhoneResponse_init_default      {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountToKeyResponse_init_default        {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define TimeRequest_init_default                 {false, 0}
#define TimeResponse_init_default                {false, 0}
#define PasswordRequest_init_default             {false, {0, {0}}}
#define PasswordResponse_init_default            {0}
#define MotorRequest_init_default                {false, (MOTOR_STATUS_TYPE)0}
#define MotorResponse_init_default               {false, (MOTOR_STATUS_TYPE)0}
#define AccountMapCheckRequest_init_default      {false, 0}
#define AccountMapCheckResponse_init_default     {false, (ACCOUNT_MAP_STATUS_TYPE)0}
#define AccountMapSyncRequest_init_default       {false, 0, false, {0, {0}}}
#define AccountMapSyncResponse_init_default      {false, (ACCOUNT_MAP_STATUS_TYPE)0}
#define AccountCheckRequest_init_default         {false, 0, false, 0}
#define AccountCheckResponse_init_default        {false, (ACCOUNT_MAP_STATUS_TYPE)0}
#define KeyMapCheckRequest_init_default          {false, 0}
#define KeyMapCheckResponse_init_default         {false, (KEY_MAP_STATUS_TYPE)0}
#define KeyMapSyncRequest_init_default           {false, 0, false, {0, {0}}}
#define KeyMapSyncResponse_init_default          {false, (KEY_MAP_STATUS_TYPE)0}
#define KeyCheckRequest_init_default             {false, 0, false, 0}
#define KeyCheckResponse_init_default            {false, (KEY_MAP_STATUS_TYPE)0}
#define PhoneMapCheckRequest_init_default        {false, 0}
#define PhoneMapCheckResponse_init_default       {false, (PHONE_MAP_STATUS_TYPE)0}
#define PhoneMapSyncRequest_init_default         {false, 0, false, {0, {0}}}
#define PhoneMapSyncResponse_init_default        {false, (PHONE_MAP_STATUS_TYPE)0}
#define PhoneCheckRequest_init_default           {false, 0, false, 0}
#define PhoneCheckResponse_init_default          {false, (PHONE_MAP_STATUS_TYPE)0}
#define LogMapCheckRequest_init_default          {false, 0}
#define LogMapCheckResponse_init_default         {false, (LOG_MAP_STATUS_TYPE)0}
#define LogMapSyncRequest_init_default           {false, 0, false, {0, {0}}}
#define LogMapSyncResponse_init_default          {false, (LOG_MAP_STATUS_TYPE)0}
#define LogCheckRequest_init_default             {false, 0, false, 0}
#define LogCheckResponse_init_default            {false, (LOG_MAP_STATUS_TYPE)0}
#define Request_init_default                     {false, LoginRequest_init_default, false, LogoutRequest_init_default, false, KeepAliveRequest_init_default, false, WorkAlarmRequest_init_default, false, FaultAlarmRequest_init_default, false, BatteryRequest_init_default, false, OpenRequest_init_default, false, TimeRequest_init_default, false, MotorRequest_init_default, false, AccountAddRequest_init_default, false, AccountModifyRequest_init_default, false, AccountDeleteRequest_init_default, false, PhoneAddRequest_init_default, false, PhoneModifyRequest_init_default, false, PhoneDeleteRequest_init_default, false, KeyAddRequest_init_default, false, KeyModifyRequest_init_default, false, KeyDeleteRequest_init_default, false, PasswordRequest_init_default, false, LogMapCheckRequest_init_default, false, LogMapSyncRequest_init_default, false, LogCheckRequest_init_default, false, AccountMapCheckRequest_init_default, false, AccountMapSyncRequest_init_default, false, AccountCheckRequest_init_default, false, KeyMapCheckRequest_init_default, false, KeyMapSyncRequest_init_default, false, KeyCheckRequest_init_default, false, PhoneMapCheckRequest_init_default, false, PhoneMapSyncRequest_init_default, false, PhoneCheckRequest_init_default, false, AccountToPhoneRequest_init_default, false, AccountToKeyRequest_init_default}
#define Response_init_default                    {0, 0, false, LoginResponse_init_default, false, LogoutResponse_init_default, false, KeepAliveResponse_init_default, false, WorkAlarmResponse_init_default, false, FaultAlarmResponse_init_default, false, BatteryResponse_init_default, false, OpenResponse_init_default, false, TimeResponse_init_default, false, MotorResponse_init_default, false, AccountAddResponse_init_default, false, AccountModifyResponse_init_default, false, AccountDeleteResponse_init_default, false, PhoneAddResponse_init_default, false, PhoneModifyResponse_init_default, false, PhoneDeleteResponse_init_default, false, KeyAddResponse_init_default, false, KeyModifyResponse_init_default, false, KeyDeleteResponse_init_default, false, PasswordResponse_init_default, false, LogMapCheckResponse_init_default, false, LogMapSyncResponse_init_default, false, LogCheckResponse_init_default, false, AccountMapCheckResponse_init_default, false, AccountMapSyncResponse_init_default, false, AccountCheckResponse_init_default, false, KeyMapCheckResponse_init_default, false, KeyMapSyncResponse_init_default, false, KeyCheckResponse_init_default, false, PhoneMapCheckResponse_init_default, false, PhoneMapSyncResponse_init_default, false, PhoneCheckResponse_init_default, false, AccountToPhoneResponse_init_default, false, AccountToKeyResponse_init_default}
#define Message_init_default                     {false, (MSG)0, false, 0, false, 0, false, Request_init_default, false, Response_init_default}
#define LoginRequest_init_zero                   {false, {0, {0}}, false, {0, {0}}, false, 0, false, {0, {0}}}
#define LoginResponse_init_zero                  {false, (LOGIN_STATUS_TYPE)0, false, 0}
#define LogoutRequest_init_zero                  {0}
#define LogoutResponse_init_zero                 {0}
#define KeepAliveRequest_init_zero               {0}
#define KeepAliveResponse_init_zero              {0}
#define WorkAlarmRequest_init_zero               {false, (WORK_ALARM_TYPE)0, false, (LOCK_STATUS_TYPE)0, false, 0}
#define WorkAlarmResponse_init_zero              {0}
#define FaultAlarmRequest_init_zero              {false, (FAULT_ALARM_TYPE)0, false, (LOCK_STATUS_TYPE)0, false, 0}
#define FaultAlarmResponse_init_zero             {0}
#define BatteryRequest_init_zero                 {false, (BATTERY_STATUS_TYPE)0, false, 0, false, 0}
#define BatteryResponse_init_zero                {0}
#define OpenRequest_init_zero                    {false, (OPEN_PATTERN_TYPE)0, false, 0, false, 0, false, (LOCK_STATUS_TYPE)0, false, 0}
#define OpenResponse_init_zero                   {0}
#define PhoneAddRequest_init_zero                {false, 0, false, (PHONE_AUTH_TYPE)0, false, "", false, 0}
#define PhoneModifyRequest_init_zero             {false, 0, false, (PHONE_AUTH_TYPE)0, false, "", false, 0}
#define PhoneDeleteRequest_init_zero             {false, 0, false, 0}
#define PhoneAddResponse_init_zero               {false, (PHONE_STATUS_TYPE)0, false, 0}
#define PhoneModifyResponse_init_zero            {false, (PHONE_STATUS_TYPE)0, false, 0}
#define PhoneDeleteResponse_init_zero            {false, (PHONE_STATUS_TYPE)0, false, 0}
#define KeyAddRequest_init_zero                  {false, 0, false, (KEY_TYPE)0, false, 0, false, (KEY_AUTH_TYPE)0, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}}
#define KeyModifyRequest_init_zero               {false, 0, false, (KEY_TYPE)0, false, 0, false, (KEY_AUTH_TYPE)0, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}}
#define KeyDeleteRequest_init_zero               {false, 0, false, 0}
#define KeyAddResponse_init_zero                 {false, (KEY_STATUS_TYPE)0, false, 0}
#define KeyModifyResponse_init_zero              {false, (KEY_STATUS_TYPE)0, false, 0}
#define KeyDeleteResponse_init_zero              {false, (KEY_STATUS_TYPE)0, false, 0}
#define AccountAddRequest_init_zero              {false, 0, false, "", false, 0}
#define AccountAddResponse_init_zero             {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountModifyRequest_init_zero           {false, 0, false, "", false, 0}
#define AccountModifyResponse_init_zero          {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountDeleteRequest_init_zero           {false, 0, false, 0}
#define AccountDeleteResponse_init_zero          {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountToPhoneRequest_init_zero          {false, 0, false, 0, false, 0}
#define AccountToKeyRequest_init_zero            {false, 0, false, 0, false, 0}
#define AccountToPhoneResponse_init_zero         {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define AccountToKeyResponse_init_zero           {false, (ACCOUNT_STATUS_TYPE)0, false, 0}
#define TimeRequest_init_zero                    {false, 0}
#define TimeResponse_init_zero                   {false, 0}
#define PasswordRequest_init_zero                {false, {0, {0}}}
#define PasswordResponse_init_zero               {0}
#define MotorRequest_init_zero                   {false, (MOTOR_STATUS_TYPE)0}
#define MotorResponse_init_zero                  {false, (MOTOR_STATUS_TYPE)0}
#define AccountMapCheckRequest_init_zero         {false, 0}
#define AccountMapCheckResponse_init_zero        {false, (ACCOUNT_MAP_STATUS_TYPE)0}
#define AccountMapSyncRequest_init_zero          {false, 0, false, {0, {0}}}
#define AccountMapSyncResponse_init_zero         {false, (ACCOUNT_MAP_STATUS_TYPE)0}
#define AccountCheckRequest_init_zero            {false, 0, false, 0}
#define AccountCheckResponse_init_zero           {false, (ACCOUNT_MAP_STATUS_TYPE)0}
#define KeyMapCheckRequest_init_zero             {false, 0}
#define KeyMapCheckResponse_init_zero            {false, (KEY_MAP_STATUS_TYPE)0}
#define KeyMapSyncRequest_init_zero              {false, 0, false, {0, {0}}}
#define KeyMapSyncResponse_init_zero             {false, (KEY_MAP_STATUS_TYPE)0}
#define KeyCheckRequest_init_zero                {false, 0, false, 0}
#define KeyCheckResponse_init_zero               {false, (KEY_MAP_STATUS_TYPE)0}
#define PhoneMapCheckRequest_init_zero           {false, 0}
#define PhoneMapCheckResponse_init_zero          {false, (PHONE_MAP_STATUS_TYPE)0}
#define PhoneMapSyncRequest_init_zero            {false, 0, false, {0, {0}}}
#define PhoneMapSyncResponse_init_zero           {false, (PHONE_MAP_STATUS_TYPE)0}
#define PhoneCheckRequest_init_zero              {false, 0, false, 0}
#define PhoneCheckResponse_init_zero             {false, (PHONE_MAP_STATUS_TYPE)0}
#define LogMapCheckRequest_init_zero             {false, 0}
#define LogMapCheckResponse_init_zero            {false, (LOG_MAP_STATUS_TYPE)0}
#define LogMapSyncRequest_init_zero              {false, 0, false, {0, {0}}}
#define LogMapSyncResponse_init_zero             {false, (LOG_MAP_STATUS_TYPE)0}
#define LogCheckRequest_init_zero                {false, 0, false, 0}
#define LogCheckResponse_init_zero               {false, (LOG_MAP_STATUS_TYPE)0}
#define Request_init_zero                        {false, LoginRequest_init_zero, false, LogoutRequest_init_zero, false, KeepAliveRequest_init_zero, false, WorkAlarmRequest_init_zero, false, FaultAlarmRequest_init_zero, false, BatteryRequest_init_zero, false, OpenRequest_init_zero, false, TimeRequest_init_zero, false, MotorRequest_init_zero, false, AccountAddRequest_init_zero, false, AccountModifyRequest_init_zero, false, AccountDeleteRequest_init_zero, false, PhoneAddRequest_init_zero, false, PhoneModifyRequest_init_zero, false, PhoneDeleteRequest_init_zero, false, KeyAddRequest_init_zero, false, KeyModifyRequest_init_zero, false, KeyDeleteRequest_init_zero, false, PasswordRequest_init_zero, false, LogMapCheckRequest_init_zero, false, LogMapSyncRequest_init_zero, false, LogCheckRequest_init_zero, false, AccountMapCheckRequest_init_zero, false, AccountMapSyncRequest_init_zero, false, AccountCheckRequest_init_zero, false, KeyMapCheckRequest_init_zero, false, KeyMapSyncRequest_init_zero, false, KeyCheckRequest_init_zero, false, PhoneMapCheckRequest_init_zero, false, PhoneMapSyncRequest_init_zero, false, PhoneCheckRequest_init_zero, false, AccountToPhoneRequest_init_zero, false, AccountToKeyRequest_init_zero}
#define Response_init_zero                       {0, 0, false, LoginResponse_init_zero, false, LogoutResponse_init_zero, false, KeepAliveResponse_init_zero, false, WorkAlarmResponse_init_zero, false, FaultAlarmResponse_init_zero, false, BatteryResponse_init_zero, false, OpenResponse_init_zero, false, TimeResponse_init_zero, false, MotorResponse_init_zero, false, AccountAddResponse_init_zero, false, AccountModifyResponse_init_zero, false, AccountDeleteResponse_init_zero, false, PhoneAddResponse_init_zero, false, PhoneModifyResponse_init_zero, false, PhoneDeleteResponse_init_zero, false, KeyAddResponse_init_zero, false, KeyModifyResponse_init_zero, false, KeyDeleteResponse_init_zero, false, PasswordResponse_init_zero, false, LogMapCheckResponse_init_zero, false, LogMapSyncResponse_init_zero, false, LogCheckResponse_init_zero, false, AccountMapCheckResponse_init_zero, false, AccountMapSyncResponse_init_zero, false, AccountCheckResponse_init_zero, false, KeyMapCheckResponse_init_zero, false, KeyMapSyncResponse_init_zero, false, KeyCheckResponse_init_zero, false, PhoneMapCheckResponse_init_zero, false, PhoneMapSyncResponse_init_zero, false, PhoneCheckResponse_init_zero, false, AccountToPhoneResponse_init_zero, false, AccountToKeyResponse_init_zero}
#define Message_init_zero                        {false, (MSG)0, false, 0, false, 0, false, Request_init_zero, false, Response_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define AccountAddRequest_id_tag                 1
#define AccountAddRequest_name_tag               2
#define AccountAddRequest_occurred_time_tag      3
#define AccountAddResponse_status_tag            1
#define AccountAddResponse_id_tag                2
#define AccountCheckRequest_time_tag             1
#define AccountCheckRequest_id_tag               2
#define AccountCheckResponse_status_tag          1
#define AccountDeleteRequest_id_tag              1
#define AccountDeleteRequest_occurred_time_tag   2
#define AccountDeleteResponse_status_tag         1
#define AccountDeleteResponse_id_tag             2
#define AccountMapCheckRequest_time_tag          1
#define AccountMapCheckResponse_status_tag       1
#define AccountMapSyncRequest_time_tag           1
#define AccountMapSyncRequest_map_tag            2
#define AccountMapSyncResponse_status_tag        1
#define AccountModifyRequest_id_tag              1
#define AccountModifyRequest_name_tag            2
#define AccountModifyRequest_occurred_time_tag   3
#define AccountModifyResponse_status_tag         1
#define AccountModifyResponse_id_tag             2
#define AccountToKeyRequest_account_id_tag       1
#define AccountToKeyRequest_key_id_tag           2
#define AccountToKeyRequest_occurred_time_tag    3
#define AccountToKeyResponse_status_tag          1
#define AccountToKeyResponse_id_tag              2
#define AccountToPhoneRequest_account_id_tag     1
#define AccountToPhoneRequest_phone_id_tag       2
#define AccountToPhoneRequest_occurred_time_tag  3
#define AccountToPhoneResponse_status_tag        1
#define AccountToPhoneResponse_id_tag            2
#define BatteryRequest_status_tag                1
#define BatteryRequest_capacity_tag              2
#define BatteryRequest_occurred_time_tag         3
#define FaultAlarmRequest_type_tag               1
#define FaultAlarmRequest_status_tag             2
#define FaultAlarmRequest_occurred_time_tag      3
#define KeyAddRequest_id_tag                     1
#define KeyAddRequest_key_type_tag               2
#define KeyAddRequest_occurred_time_tag          3
#define KeyAddRequest_auth_type_tag              4
#define KeyAddRequest_weekly_tag                 5
#define KeyAddRequest_start_time_tag             6
#define KeyAddRequest_end_time_tag               7
#define KeyAddRequest_code_tag                   8
#define KeyAddResponse_status_tag                1
#define KeyAddResponse_id_tag                    2
#define KeyCheckRequest_time_tag                 1
#define KeyCheckRequest_id_tag                   2
#define KeyCheckResponse_status_tag              1
#define KeyDeleteRequest_id_tag                  1
#define KeyDeleteRequest_occurred_time_tag       2
#define KeyDeleteResponse_status_tag             1
#define KeyDeleteResponse_id_tag                 2
#define KeyMapCheckRequest_time_tag              1
#define KeyMapCheckResponse_status_tag           1
#define KeyMapSyncRequest_time_tag               1
#define KeyMapSyncRequest_map_tag                2
#define KeyMapSyncResponse_status_tag            1
#define KeyModifyRequest_id_tag                  1
#define KeyModifyRequest_key_type_tag            2
#define KeyModifyRequest_occurred_time_tag       3
#define KeyModifyRequest_auth_type_tag           4
#define KeyModifyRequest_weekly_tag              5
#define KeyModifyRequest_start_time_tag          6
#define KeyModifyRequest_end_time_tag            7
#define KeyModifyRequest_code_tag                8
#define KeyModifyResponse_status_tag             1
#define KeyModifyResponse_id_tag                 2
#define LogCheckRequest_time_tag                 1
#define LogCheckRequest_id_tag                   2
#define LogCheckResponse_status_tag              1
#define LogMapCheckRequest_time_tag              1
#define LogMapCheckResponse_status_tag           1
#define LogMapSyncRequest_time_tag               1
#define LogMapSyncRequest_map_tag                2
#define LogMapSyncResponse_status_tag            1
#define LoginRequest_id_tag                      1
#define LoginRequest_k1_tag                      2
#define LoginRequest_version_tag                 3
#define LoginRequest_k0_tag                      4
#define LoginResponse_status_tag                 1
#define LoginResponse_server_time_tag            2
#define MotorRequest_status_tag                  1
#define MotorResponse_status_tag                 1
#define OpenRequest_type_tag                     1
#define OpenRequest_account_id_tag               2
#define OpenRequest_key_id_tag                   3
#define OpenRequest_status_tag                   4
#define OpenRequest_occurred_time_tag            5
#define PasswordRequest_k0_tag                   1
#define PhoneAddRequest_id_tag                   1
#define PhoneAddRequest_type_tag                 2
#define PhoneAddRequest_number_tag               3
#define PhoneAddRequest_occurred_time_tag        4
#define PhoneAddResponse_status_tag              1
#define PhoneAddResponse_id_tag                  2
#define PhoneCheckRequest_time_tag               1
#define PhoneCheckRequest_id_tag                 2
#define PhoneCheckResponse_status_tag            1
#define PhoneDeleteRequest_id_tag                1
#define PhoneDeleteRequest_occurred_time_tag     2
#define PhoneDeleteResponse_status_tag           1
#define PhoneDeleteResponse_id_tag               2
#define PhoneMapCheckRequest_time_tag            1
#define PhoneMapCheckResponse_status_tag         1
#define PhoneMapSyncRequest_time_tag             1
#define PhoneMapSyncRequest_map_tag              2
#define PhoneMapSyncResponse_status_tag          1
#define PhoneModifyRequest_id_tag                1
#define PhoneModifyRequest_type_tag              2
#define PhoneModifyRequest_number_tag            3
#define PhoneModifyRequest_occurred_time_tag     4
#define PhoneModifyResponse_status_tag           1
#define PhoneModifyResponse_id_tag               2
#define TimeRequest_time_tag                     1
#define TimeResponse_time_tag                    1
#define WorkAlarmRequest_type_tag                1
#define WorkAlarmRequest_status_tag              2
#define WorkAlarmRequest_occurred_time_tag       3
#define Request_login_tag                        1
#define Request_logout_tag                       2
#define Request_keepalive_tag                    3
#define Request_workalarm_tag                    4
#define Request_faultalarm_tag                   5
#define Request_battery_tag                      6
#define Request_open_tag                         7
#define Request_time_tag                         9
#define Request_motor_tag                        11
#define Request_account_add_tag                  14
#define Request_account_modify_tag               15
#define Request_account_delete_tag               16
#define Request_phone_add_tag                    17
#define Request_phone_modify_tag                 18
#define Request_phone_delete_tag                 19
#define Request_key_add_tag                      20
#define Request_key_modify_tag                   21
#define Request_key_delete_tag                   22
#define Request_password_tag                     23
#define Request_log_map_check_tag                24
#define Request_log_map_sync_tag                 25
#define Request_log_check_tag                    26
#define Request_account_map_check_tag            27
#define Request_account_map_sync_tag             28
#define Request_account_check_tag                29
#define Request_key_map_check_tag                30
#define Request_key_map_sync_tag                 31
#define Request_key_check_tag                    32
#define Request_phone_map_check_tag              33
#define Request_phone_map_sync_tag               34
#define Request_phone_check_tag                  35
#define Request_account_to_phone_tag             37
#define Request_account_to_key_tag               38
#define Response_result_tag                      1
#define Response_last_response_tag               2
#define Response_login_tag                       3
#define Response_logout_tag                      4
#define Response_keepalive_tag                   5
#define Response_workalarm_tag                   6
#define Response_faultalarm_tag                  7
#define Response_battery_tag                     8
#define Response_open_tag                        9
#define Response_time_tag                        12
#define Response_motor_tag                       14
#define Response_account_add_tag                 17
#define Response_account_modify_tag              18
#define Response_account_delete_tag              19
#define Response_phone_add_tag                   20
#define Response_phone_modify_tag                21
#define Response_phone_delete_tag                22
#define Response_key_add_tag                     23
#define Response_key_modify_tag                  24
#define Response_key_delete_tag                  25
#define Response_password_tag                    26
#define Response_log_map_check_tag               27
#define Response_log_map_sync_tag                28
#define Response_log_check_tag                   29
#define Response_account_map_check_tag           30
#define Response_account_map_sync_tag            31
#define Response_account_check_tag               32
#define Response_key_map_check_tag               33
#define Response_key_map_sync_tag                34
#define Response_key_check_tag                   35
#define Response_phone_map_check_tag             36
#define Response_phone_map_sync_tag              37
#define Response_phone_check_tag                 38
#define Response_account_to_phone_tag            40
#define Response_account_to_key_tag              41
#define Message_msg_type_tag                     1
#define Message_sequence_tag                     2
#define Message_session_id_tag                   3
#define Message_request_tag                      4
#define Message_response_tag                     5

/* Struct field encoding specification for nanopb */
extern const pb_field_t LoginRequest_fields[5];
extern const pb_field_t LoginResponse_fields[3];
extern const pb_field_t LogoutRequest_fields[1];
extern const pb_field_t LogoutResponse_fields[1];
extern const pb_field_t KeepAliveRequest_fields[1];
extern const pb_field_t KeepAliveResponse_fields[1];
extern const pb_field_t WorkAlarmRequest_fields[4];
extern const pb_field_t WorkAlarmResponse_fields[1];
extern const pb_field_t FaultAlarmRequest_fields[4];
extern const pb_field_t FaultAlarmResponse_fields[1];
extern const pb_field_t BatteryRequest_fields[4];
extern const pb_field_t BatteryResponse_fields[1];
extern const pb_field_t OpenRequest_fields[6];
extern const pb_field_t OpenResponse_fields[1];
extern const pb_field_t PhoneAddRequest_fields[5];
extern const pb_field_t PhoneModifyRequest_fields[5];
extern const pb_field_t PhoneDeleteRequest_fields[3];
extern const pb_field_t PhoneAddResponse_fields[3];
extern const pb_field_t PhoneModifyResponse_fields[3];
extern const pb_field_t PhoneDeleteResponse_fields[3];
extern const pb_field_t KeyAddRequest_fields[9];
extern const pb_field_t KeyModifyRequest_fields[9];
extern const pb_field_t KeyDeleteRequest_fields[3];
extern const pb_field_t KeyAddResponse_fields[3];
extern const pb_field_t KeyModifyResponse_fields[3];
extern const pb_field_t KeyDeleteResponse_fields[3];
extern const pb_field_t AccountAddRequest_fields[4];
extern const pb_field_t AccountAddResponse_fields[3];
extern const pb_field_t AccountModifyRequest_fields[4];
extern const pb_field_t AccountModifyResponse_fields[3];
extern const pb_field_t AccountDeleteRequest_fields[3];
extern const pb_field_t AccountDeleteResponse_fields[3];
extern const pb_field_t AccountToPhoneRequest_fields[4];
extern const pb_field_t AccountToKeyRequest_fields[4];
extern const pb_field_t AccountToPhoneResponse_fields[3];
extern const pb_field_t AccountToKeyResponse_fields[3];
extern const pb_field_t TimeRequest_fields[2];
extern const pb_field_t TimeResponse_fields[2];
extern const pb_field_t PasswordRequest_fields[2];
extern const pb_field_t PasswordResponse_fields[1];
extern const pb_field_t MotorRequest_fields[2];
extern const pb_field_t MotorResponse_fields[2];
extern const pb_field_t AccountMapCheckRequest_fields[2];
extern const pb_field_t AccountMapCheckResponse_fields[2];
extern const pb_field_t AccountMapSyncRequest_fields[3];
extern const pb_field_t AccountMapSyncResponse_fields[2];
extern const pb_field_t AccountCheckRequest_fields[3];
extern const pb_field_t AccountCheckResponse_fields[2];
extern const pb_field_t KeyMapCheckRequest_fields[2];
extern const pb_field_t KeyMapCheckResponse_fields[2];
extern const pb_field_t KeyMapSyncRequest_fields[3];
extern const pb_field_t KeyMapSyncResponse_fields[2];
extern const pb_field_t KeyCheckRequest_fields[3];
extern const pb_field_t KeyCheckResponse_fields[2];
extern const pb_field_t PhoneMapCheckRequest_fields[2];
extern const pb_field_t PhoneMapCheckResponse_fields[2];
extern const pb_field_t PhoneMapSyncRequest_fields[3];
extern const pb_field_t PhoneMapSyncResponse_fields[2];
extern const pb_field_t PhoneCheckRequest_fields[3];
extern const pb_field_t PhoneCheckResponse_fields[2];
extern const pb_field_t LogMapCheckRequest_fields[2];
extern const pb_field_t LogMapCheckResponse_fields[2];
extern const pb_field_t LogMapSyncRequest_fields[3];
extern const pb_field_t LogMapSyncResponse_fields[2];
extern const pb_field_t LogCheckRequest_fields[3];
extern const pb_field_t LogCheckResponse_fields[2];
extern const pb_field_t Request_fields[34];
extern const pb_field_t Response_fields[36];
extern const pb_field_t Message_fields[6];

/* Maximum encoded size of messages (where known) */
#define LoginRequest_size                        59
#define LoginResponse_size                       11
#define LogoutRequest_size                       0
#define LogoutResponse_size                      0
#define KeepAliveRequest_size                    0
#define KeepAliveResponse_size                   0
#define WorkAlarmRequest_size                    17
#define WorkAlarmResponse_size                   0
#define FaultAlarmRequest_size                   17
#define FaultAlarmResponse_size                  0
#define BatteryRequest_size                      16
#define BatteryResponse_size                     0
#define OpenRequest_size                         27
#define OpenResponse_size                        0
#define PhoneAddRequest_size                     34
#define PhoneModifyRequest_size                  34
#define PhoneDeleteRequest_size                  10
#define PhoneAddResponse_size                    11
#define PhoneModifyResponse_size                 11
#define PhoneDeleteResponse_size                 11
#define KeyAddRequest_size                       68
#define KeyModifyRequest_size                    68
#define KeyDeleteRequest_size                    10
#define KeyAddResponse_size                      11
#define KeyModifyResponse_size                   11
#define KeyDeleteResponse_size                   11
#define AccountAddRequest_size                   28
#define AccountAddResponse_size                  11
#define AccountModifyRequest_size                28
#define AccountModifyResponse_size               11
#define AccountDeleteRequest_size                10
#define AccountDeleteResponse_size               11
#define AccountToPhoneRequest_size               15
#define AccountToKeyRequest_size                 15
#define AccountToPhoneResponse_size              11
#define AccountToKeyResponse_size                11
#define TimeRequest_size                         5
#define TimeResponse_size                        5
#define PasswordRequest_size                     18
#define PasswordResponse_size                    0
#define MotorRequest_size                        6
#define MotorResponse_size                       6
#define AccountMapCheckRequest_size              5
#define AccountMapCheckResponse_size             6
#define AccountMapSyncRequest_size               520
#define AccountMapSyncResponse_size              6
#define AccountCheckRequest_size                 10
#define AccountCheckResponse_size                6
#define KeyMapCheckRequest_size                  5
#define KeyMapCheckResponse_size                 6
#define KeyMapSyncRequest_size                   520
#define KeyMapSyncResponse_size                  6
#define KeyCheckRequest_size                     10
#define KeyCheckResponse_size                    6
#define PhoneMapCheckRequest_size                5
#define PhoneMapCheckResponse_size               6
#define PhoneMapSyncRequest_size                 520
#define PhoneMapSyncResponse_size                6
#define PhoneCheckRequest_size                   10
#define PhoneCheckResponse_size                  6
#define LogMapCheckRequest_size                  5
#define LogMapCheckResponse_size                 6
#define LogMapSyncRequest_size                   520
#define LogMapSyncResponse_size                  6
#define LogCheckRequest_size                     10
#define LogCheckResponse_size                    6
#define Request_size                             2717
#define Response_size                            309
#define Message_size                             3048

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
